server:
  port: 80

spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/springboot?serverTimezone=UTC
      username: root
      password: lxh


mybatis-plus:
  globel-config:
    db-config:
      table-prefix: tb_
      id-type: auto
